loot: # specifies what files to pull the loot tables from (in loot folder)
  daily:
    files:
      - 'daily.json'
  premium:
    files:
      - 'premium.json'
  vote:
    files:
      - 'vote.json'
services:
  - 'Test1'
  - 'Test2'
  - 'Test3'
  - 'Test4'
  - 'Test5'
  - 'Test6'
free-premium-crate:
  enable: true
  rules:
    check: false # Disable for default, minor improvement in performance
    default: 7 # Days
    diamond: 3
  amount:
    check: false # Disable for default, minor improvement in performance
    default: 1
    diamond: 2
menu:
  enable-animation: true # enables the 'animation' in the menu
  khavalon: true
  update-ticks: 2 # Speed at which the menu should update at
  sounds: # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html for list of sounds
    center:
      volume: 1
      pitch: 1
      sound: UI_BUTTON_CLICK
    reveal: # When all items finished revealing or claim all button is clicked
      volume: 1
      pitch: 1
      sound: ENTITY_FIREWORK_ROCKET_LAUNCH
  claim-lore: #lore added when claiming items
    - '<green>Click to claim this item!'
  unclaimed-items:
    - '<green>You still have unclaimed items!'
    - '<gray>Click to claim them!'
  items:
    daily:
      name: '<green>Daily Crates'
      material: 'BARREL'
      can-use:
        lore:
          - '<green>You have {count} crates to claim!'
          - '<gray>Click to claim the daily crates!'
      cant-use:
        lore:
          - '<red>You have already opened the daily crate today!'
    premium:
      name: '<green>Premium Crates'
      material: 'ENDER_CHEST'
      can-use:
        lore:
          - '<green>You have {count} crates to claim!'
          - '<gray>Click to claim the premium crates!'
      cant-use:
        lore:
          - '<gray>{days}/{max_days} Days completed.'
          - '<red>You don''t have any premium crates! Buy more at <gradient:yellow:red>store.semivanilla.com</gradient>'
    vote:
      name: '<green>Vote'
      material: 'CHEST'
      can-use:
        lore:
          - '<green>You have {count} crates to claim!'
          - '<gray>Click to claim the vote crates!'
      cant-use:
        lore:
          - '<red>You don''t have any vote crates! Do <gradient:yellow:red>/vote</gradient> to get more!'
messages:
  crates-left:
    - '<green>You still have {count} crates to claim! use <gradient:yellow:red>/crates</gradient> to claim them!</green>'
  crates-earned-offline:
    - '<green>You gained {count} crates while away! Use <gradient:yellow:red>/crates</gradient> to claim your rewards.</green>'
  crates-gained:
    - '<green>You have been given {count} {type} crate(s)!'
  vote:
    - '<green>Thanks for voting! You completed a Vote Crate!'
  inventory-full:
    - '<red>Your inventory is full!'
vote-processor:
  async: true
  interval: 5
